In [1]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [2]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range (len(sequence)):
        end_ix = i+n_steps
        
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        
        X.append(seq_x)
        y.append(seq_y)
        
    return array(X), array(y)

In [3]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

n_steps=3

X, y = split_sequence(raw_seq, n_steps)
for i in range(len(X)):
    print(X[i], y[i])
    
n_features = 1
X= X.reshape((X.shape[0], X.shape[1], n_features))

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [4]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X,y, epochs=2000, verbose=1)
x_input = array([90,100,110])

Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 4204.8687
Epoch 2/2000
1/1 [==============================] - 0s 4ms/step - loss: 4165.1035
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 4126.8296
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 4090.3035
Epoch 5/2000
1/1 [==============================] - 0s 5ms/step - loss: 4055.1892
Epoch 6/2000
1/1 [==============================] - 0s 4ms/step - loss: 4021.2102
Epoch 7/2000
1/1 [==============================] - 0s 4ms/step - loss: 3988.1672
Epoch 8/2000
1/1 [==============================] - 0s 5ms/step - loss: 3955.9861
Epoch 9/2000
1/1 [==============================] - 0s 1ms/step - loss: 3924.5078
Epoch 10/2000
1/1 [==============================] - 0s 4ms/step - loss: 3893.6243
Epoch 11/2000
1/1 [==============================] - 0s 2ms/step - loss: 3863.3206
Epoch 12/2000
1/1 [==============================] - 0s 3ms/step - loss: 3833.5452
Epoch 13/2000

1/1 [==============================] - 0s 2ms/step - loss: 36.4053
Epoch 101/2000
1/1 [==============================] - 0s 3ms/step - loss: 35.0838
Epoch 102/2000
1/1 [==============================] - 0s 2ms/step - loss: 33.4265
Epoch 103/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.5328
Epoch 104/2000
1/1 [==============================] - 0s 3ms/step - loss: 29.6400
Epoch 105/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.9218
Epoch 106/2000
1/1 [==============================] - 0s 3ms/step - loss: 26.4102
Epoch 107/2000
1/1 [==============================] - 0s 4ms/step - loss: 25.0426
Epoch 108/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.7359
Epoch 109/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.4332
Epoch 110/2000
1/1 [==============================] - 0s 999us/step - loss: 21.1183
Epoch 111/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.8120
Epoch 112/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 0.4669
Epoch 201/2000
1/1 [==============================] - ETA: 0s - loss: 0.456 - 0s 969us/step - loss: 0.4560
Epoch 202/2000
1/1 [==============================] - 0s 973us/step - loss: 0.4454
Epoch 203/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.4351
Epoch 204/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.4252
Epoch 205/2000
1/1 [==============================] - 0s 999us/step - loss: 0.4154
Epoch 206/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.4059
Epoch 207/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3967
Epoch 208/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3877
Epoch 209/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3790
Epoch 210/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3706
Epoch 211/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.3624
Epoch 212/200

1/1 [==============================] - 0s 2ms/step - loss: 0.0335
Epoch 301/2000
1/1 [==============================] - 0s 997us/step - loss: 0.0323
Epoch 302/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.0312
Epoch 303/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.0302
Epoch 304/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.0291
Epoch 305/2000
1/1 [==============================] - 0s 998us/step - loss: 0.0281
Epoch 306/2000
1/1 [==============================] - 0s 448us/step - loss: 0.0271
Epoch 307/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.0262
Epoch 308/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.0253
Epoch 309/2000
1/1 [==============================] - 0s 997us/step - loss: 0.0244
Epoch 310/2000
1/1 [==============================] - 0s 893us/step - loss: 0.0235
Epoch 311/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0226
Epoch 312/2000
1/1 [=============

1/1 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 401/2000
1/1 [==============================] - 0s 744us/step - loss: 0.0011
Epoch 402/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 403/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 404/2000
1/1 [==============================] - 0s 985us/step - loss: 0.0010
Epoch 405/2000
1/1 [==============================] - 0s 881us/step - loss: 0.0010
Epoch 406/2000
1/1 [==============================] - 0s 1ms/step - loss: 9.8740e-04
Epoch 407/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6581e-04
Epoch 408/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.4493e-04
Epoch 409/2000
1/1 [==============================] - 0s 998us/step - loss: 9.2355e-04
Epoch 410/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.0208e-04
Epoch 411/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.8068e-04
Epoch 412/2

1/1 [==============================] - 0s 3ms/step - loss: 1.9523e-04
Epoch 497/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.9404e-04
Epoch 498/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.9281e-04
Epoch 499/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.9155e-04
Epoch 500/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.9039e-04
Epoch 501/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8924e-04
Epoch 502/2000
1/1 [==============================] - 0s 991us/step - loss: 1.8818e-04
Epoch 503/2000
1/1 [==============================] - 0s 998us/step - loss: 1.8701e-04
Epoch 504/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8592e-04
Epoch 505/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8483e-04
Epoch 506/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8372e-04
Epoch 507/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.

1/1 [==============================] - 0s 2ms/step - loss: 1.2010e-04
Epoch 593/2000
1/1 [==============================] - 0s 997us/step - loss: 1.1953e-04
Epoch 594/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.1894e-04
Epoch 595/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1831e-04
Epoch 596/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1780e-04
Epoch 597/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.1728e-04
Epoch 598/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.1669e-04
Epoch 599/2000
1/1 [==============================] - 0s 998us/step - loss: 1.1613e-04
Epoch 600/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1553e-04
Epoch 601/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1505e-04
Epoch 602/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1451e-04
Epoch 603/2000
1/1 [==============================] - 0s 998us/step - loss: 

1/1 [==============================] - 0s 1ms/step - loss: 7.5477e-05
Epoch 689/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.5087e-05
Epoch 690/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.4752e-05
Epoch 691/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.4336e-05
Epoch 692/2000
1/1 [==============================] - 0s 969us/step - loss: 7.3978e-05
Epoch 693/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3588e-05
Epoch 694/2000
1/1 [==============================] - 0s 997us/step - loss: 7.3228e-05
Epoch 695/2000
1/1 [==============================] - 0s 854us/step - loss: 7.2840e-05
Epoch 696/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.2536e-05
Epoch 697/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.2125e-05
Epoch 698/2000
1/1 [==============================] - 0s 966us/step - loss: 7.1774e-05
Epoch 699/2000
1/1 [==============================] - 0s 2ms/step - loss

1/1 [==============================] - 0s 2ms/step - loss: 4.6249e-05
Epoch 785/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.6062e-05
Epoch 786/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.5771e-05
Epoch 787/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.5530e-05
Epoch 788/2000
1/1 [==============================] - 0s 3ms/step - loss: 4.5295e-05
Epoch 789/2000
1/1 [==============================] - 0s 522us/step - loss: 4.5078e-05
Epoch 790/2000
1/1 [==============================] - 0s 981us/step - loss: 4.4870e-05
Epoch 791/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.4594e-05
Epoch 792/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.4351e-05
Epoch 793/2000
1/1 [==============================] - 0s 6ms/step - loss: 4.4125e-05
Epoch 794/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.3933e-05
Epoch 795/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.

1/1 [==============================] - 0s 2ms/step - loss: 2.7597e-05
Epoch 881/2000
1/1 [==============================] - 0s 3ms/step - loss: 2.7428e-05
Epoch 882/2000
1/1 [==============================] - 0s 997us/step - loss: 2.7281e-05
Epoch 883/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.7177e-05
Epoch 884/2000
1/1 [==============================] - 0s 3ms/step - loss: 2.7015e-05
Epoch 885/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6848e-05
Epoch 886/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6731e-05
Epoch 887/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.6591e-05
Epoch 888/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6399e-05
Epoch 889/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6288e-05
Epoch 890/2000
1/1 [==============================] - 0s 998us/step - loss: 2.6094e-05
Epoch 891/2000
1/1 [==============================] - 0s 997us/step - loss: 

1/1 [==============================] - 0s 2ms/step - loss: 1.6000e-05
Epoch 977/2000
1/1 [==============================] - 0s 687us/step - loss: 1.5904e-05
Epoch 978/2000
1/1 [==============================] - 0s 997us/step - loss: 1.5817e-05
Epoch 979/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5752e-05
Epoch 980/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5634e-05
Epoch 981/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5546e-05
Epoch 982/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5455e-05
Epoch 983/2000
1/1 [==============================] - 0s 993us/step - loss: 1.5358e-05
Epoch 984/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.5286e-05
Epoch 985/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.5194e-05
Epoch 986/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5083e-05
Epoch 987/2000
1/1 [==============================] - 0s 2ms/step - loss: 

1/1 [==============================] - 0s 2ms/step - loss: 9.0725e-06
Epoch 1072/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.0144e-06
Epoch 1073/2000
1/1 [==============================] - 0s 997us/step - loss: 8.9552e-06
Epoch 1074/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.9194e-06
Epoch 1075/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.8395e-06
Epoch 1076/2000
1/1 [==============================] - 0s 998us/step - loss: 8.7966e-06
Epoch 1077/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.7232e-06
Epoch 1078/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.6692e-06
Epoch 1079/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.6228e-06
Epoch 1080/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.5536e-06
Epoch 1081/2000
1/1 [==============================] - 0s 996us/step - loss: 8.5041e-06
Epoch 1082/2000
1/1 [==============================] - 0s 5ms/st

1/1 [==============================] - 0s 1ms/step - loss: 4.9519e-06
Epoch 1167/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.9371e-06
Epoch 1168/2000
1/1 [==============================] - 0s 997us/step - loss: 4.8927e-06
Epoch 1169/2000
1/1 [==============================] - 0s 3ms/step - loss: 4.8629e-06
Epoch 1170/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.8340e-06
Epoch 1171/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.8091e-06
Epoch 1172/2000
1/1 [==============================] - 0s 996us/step - loss: 4.7642e-06
Epoch 1173/2000
1/1 [==============================] - 0s 4ms/step - loss: 4.7353e-06
Epoch 1174/2000
1/1 [==============================] - 0s 3ms/step - loss: 4.7078e-06
Epoch 1175/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.6757e-06
Epoch 1176/2000
1/1 [==============================] - 0s 998us/step - loss: 4.6531e-06
Epoch 1177/2000
1/1 [==============================] - 0s 4ms/st

1/1 [==============================] - 0s 4ms/step - loss: 2.6331e-06
Epoch 1262/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6135e-06
Epoch 1263/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.6038e-06
Epoch 1264/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.5775e-06
Epoch 1265/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.5553e-06
Epoch 1266/2000
1/1 [==============================] - 0s 996us/step - loss: 2.5346e-06
Epoch 1267/2000
1/1 [==============================] - 0s 998us/step - loss: 2.5331e-06
Epoch 1268/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.5056e-06
Epoch 1269/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.4870e-06
Epoch 1270/2000
1/1 [==============================] - 0s 5ms/step - loss: 2.4773e-06
Epoch 1271/2000
1/1 [==============================] - 0s 4ms/step - loss: 2.4507e-06
Epoch 1272/2000
1/1 [==============================] - 0s 2ms/step

1/1 [==============================] - 0s 2ms/step - loss: 1.3449e-06
Epoch 1357/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.3277e-06
Epoch 1358/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.3241e-06
Epoch 1359/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.3132e-06
Epoch 1360/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.3032e-06
Epoch 1361/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.2951e-06
Epoch 1362/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.2864e-06
Epoch 1363/2000
1/1 [==============================] - 0s 892us/step - loss: 1.2812e-06
Epoch 1364/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.2672e-06
Epoch 1365/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.2535e-06
Epoch 1366/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.2499e-06
Epoch 1367/2000
1/1 [==============================] - 0s 998us/step

1/1 [==============================] - 0s 3ms/step - loss: 1.7898e-05
Epoch 1452/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.6482e-05
Epoch 1453/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.2065e-05
Epoch 1454/2000
1/1 [==============================] - 0s 997us/step - loss: 7.6860e-05
Epoch 1455/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.6749e-05
Epoch 1456/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.4777e-05
Epoch 1457/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.7839e-07
Epoch 1458/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.7182e-06
Epoch 1459/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.7479e-05
Epoch 1460/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.0677e-05
Epoch 1461/2000
1/1 [==============================] - 0s 3ms/step - loss: 3.9256e-05
Epoch 1462/2000
1/1 [==============================] - 0s 2ms/step -

1/1 [==============================] - 0s 2ms/step - loss: 3.2788e-07
Epoch 1546/2000
1/1 [==============================] - 0s 2ms/step - loss: 3.3651e-07
Epoch 1547/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.4360e-07
Epoch 1548/2000
1/1 [==============================] - 0s 2ms/step - loss: 3.5562e-07
Epoch 1549/2000
1/1 [==============================] - 0s 4ms/step - loss: 3.7377e-07
Epoch 1550/2000
1/1 [==============================] - 0s 2ms/step - loss: 3.9263e-07
Epoch 1551/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.1055e-07
Epoch 1552/2000
1/1 [==============================] - 0s 3ms/step - loss: 4.3019e-07
Epoch 1553/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.5941e-07
Epoch 1554/2000
1/1 [==============================] - 0s 1ms/step - loss: 5.0006e-07
Epoch 1555/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.4435e-07
Epoch 1556/2000
1/1 [==============================] - 0s 1ms/step - l

1/1 [==============================] - 0s 2ms/step - loss: 3.4410e-07
Epoch 1641/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.2638e-08
Epoch 1642/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2105e-07
Epoch 1643/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.4701e-06
Epoch 1644/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.0613e-06
Epoch 1645/2000
1/1 [==============================] - 0s 5ms/step - loss: 2.0722e-06
Epoch 1646/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5584e-06
Epoch 1647/2000
1/1 [==============================] - 0s 997us/step - loss: 8.3386e-07
Epoch 1648/2000
1/1 [==============================] - 0s 965us/step - loss: 2.6025e-07
Epoch 1649/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.4939e-08
Epoch 1650/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.7349e-07
Epoch 1651/2000
1/1 [==============================] - 0s 2ms/step

1/1 [==============================] - 0s 2ms/step - loss: 3.9848e-08
Epoch 1736/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.1012e-08
Epoch 1737/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5525e-08
Epoch 1738/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.0147e-08
Epoch 1739/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.3185e-07
Epoch 1740/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.0500e-07
Epoch 1741/2000
1/1 [==============================] - 0s 998us/step - loss: 3.3133e-07
Epoch 1742/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.4579e-07
Epoch 1743/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.0354e-07
Epoch 1744/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.4944e-06
Epoch 1745/2000
1/1 [==============================] - 0s 5ms/step - loss: 2.4669e-06
Epoch 1746/2000
1/1 [==============================] - 0s 2ms/step -

1/1 [==============================] - 0s 2ms/step - loss: 1.5920e-06
Epoch 1831/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8808e-06
Epoch 1832/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.2169e-06
Epoch 1833/2000
1/1 [==============================] - 0s 2ms/step - loss: 3.3420e-07
Epoch 1834/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.2053e-08
Epoch 1835/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.0025e-07
Epoch 1836/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4064e-07
Epoch 1837/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.0710e-06
Epoch 1838/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9453e-07
Epoch 1839/2000
1/1 [==============================] - 0s 1000us/step - loss: 1.9885e-07
Epoch 1840/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.7904e-08
Epoch 1841/2000
1/1 [==============================] - 0s 997us/ste

1/1 [==============================] - 0s 2ms/step - loss: 7.5112e-09
Epoch 1926/2000
1/1 [==============================] - 0s 6ms/step - loss: 7.3657e-09
Epoch 1927/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9679e-09
Epoch 1928/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4360e-09
Epoch 1929/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3463e-09
Epoch 1930/2000
1/1 [==============================] - 0s 996us/step - loss: 7.0771e-09
Epoch 1931/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.1062e-09
Epoch 1932/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.7569e-09
Epoch 1933/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.1959e-09
Epoch 1934/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3972e-09
Epoch 1935/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0407e-09
Epoch 1936/2000
1/1 [==============================] - 0s 2ms/step -

In [5]:
x_in = x_input.reshape((1, n_steps, n_features))

In [6]:
yout= model.predict(x_in, verbose=0)

In [7]:
yout

array([[122.0282]], dtype=float32)

expected output= 120